name: Lint, Build & Test

on: 
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:
  lintBuildTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: NPM Install
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Compile TypeScript
      run: npm run compile

    - name: Run tests
      run: npm run test