name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Package extension
        uses: lannonbr/vsce-action@master
        with:
          args: "package -o ado-task-viewer-${{ github.event.release.tag_name }}.vsix"
      - name: Upload extension package to release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }} 
          asset_path: ./ado-task-viewer-${{ github.event.release.tag_name }}.vsix
          asset_name: ado-task-viewer-${{ github.event.release.tag_name }}.vsix
          asset_content_type: application/octet-stream
